### ISSUE TITLE
C7H2 wrong isomer count

### ISSUE THREAD

**Issue by tobigithub** [gilleain/moleculegen#1]
Hi,
java -server -Xms500M -Xmx512M -cp AMG20121014.jar app.AMG -e C7H2
358 structures

should be 356.
Confirmed with a) molgen-demo 3.5 b) SMOG2
Tobias

**Comment by gilleain** [comment]
Now get the same count as molgen for both:

java -jar build/libs/moleculegen-full.jar  -e "C7H2" 
356 structures

java -jar build/libs/moleculegen-full.jar  --augmentation=BOND -e "C7H2" 
356 structures
