### ISSUE TITLE
CH4 one isomer

### ISSUE THREAD

**Issue by tobigithub** [gilleain/moleculegen#2]
java -server -Xms500M -Xmx512M -cp AMG20121014.jar app.AMG -e CH4 
Please specify more than 1 heavy atom

Should be 1

Tobias

**Comment by gilleain** [comment]
Now fixed for both :

earwen:moleculegen maclean$ java -jar build/libs/moleculegen-full.jar --augmentation=BOND -e "CH4"
1 structures
earwen:moleculegen maclean$ java -jar build/libs/moleculegen-full.jar --augmentation=ATOM -e "CH4"
1 structures
