### ISSUE TITLE
AMG calculates with exceeding valencies

### ISSUE THREAD

**Issue by tobigithub** [gilleain/moleculegen#5]
Hi,
exceeding valencies should directly generate an error for common elements.

amg -e C7H18 -O SMI
keeps calculating instead of saying, no solution possible > (2n+2).
Same is true for N,O,P,S

This is AMG20121014
Tobias

**Comment by gilleain** [comment]
No longer happens:

java -jar build/libs/moleculegen-full.jar  --augmentation=ATOM -e "C7H18" 
0 structures
java -jar build/libs/moleculegen-full.jar  --augmentation=BOND -e "C7H18" 
0 structures

**Comment by tobigithub** [comment]
Tnx.
